//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWcfApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstMessage
    {
        public FirstMessage()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public int SourceUserId { get; set; }
        public int TargetUserId { get; set; }
        public string Date { get; set; }
        public bool MatchFound { get; set; }
        public string SubjectName { get; set; }
        public bool SourceUserDeleted { get; set; }
        public bool TargetUserDeleted { get; set; }
        public Nullable<System.DateTime> LastTimeSourceUserTyped { get; set; }
        public Nullable<System.DateTime> LastTimeTargetUserTyped { get; set; }
    
        public virtual User SourceUser { get; set; }
        public virtual User TargetUser { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
