//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWcfApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hint
    {
        public Hint()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string PictureLink { get; set; }
        public string VideoLink { get; set; }
        public byte[] ThumbnailImage { get; set; }
        public string Size { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
