//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWcfApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FirstMessagesFromSourceUser = new HashSet<FirstMessage>();
            this.FirstMessagesFromTargetUser = new HashSet<FirstMessage>();
            this.MessagesAsSourceUser = new HashSet<Message>();
            this.MessagesAsTargetUser = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string FacebookUserId { get; set; }
        public string GoogleUserId { get; set; }
        public string PhoneNumber { get; set; }
        public string ProfileImageLink { get; set; }
        public string LastSeen { get; set; }
        public string VerificationCode { get; set; }
        public bool Verified { get; set; }
        public string DeviceId { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<FirstMessage> FirstMessagesFromSourceUser { get; set; }
        public virtual ICollection<FirstMessage> FirstMessagesFromTargetUser { get; set; }
        public virtual ICollection<Message> MessagesAsSourceUser { get; set; }
        public virtual ICollection<Message> MessagesAsTargetUser { get; set; }
    }
}
