//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWcfApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FirstMessages = new HashSet<FirstMessage>();
            this.FirstMessages1 = new HashSet<FirstMessage>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string FacebookUserId { get; set; }
        public string GoogleUserId { get; set; }
        public string PhoneNumber { get; set; }
        public string ProfileImageLink { get; set; }
        public string LastSeen { get; set; }
        public string VerificationCode { get; set; }
        public bool Verified { get; set; }
        public string DeviceId { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<FirstMessage> FirstMessages { get; set; }
        public virtual ICollection<FirstMessage> FirstMessages1 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
    }
}
